//! Poseidon2 hash function over Goldilocks, with full trace recording.
//!
//! This module is used in two ways:
//!   1. By the trace generator (trace.rs) to compute hashes AND record every
//!      intermediate state for embedding in the STARK execution trace.
//!   2. By standalone callers (tests, wasm) who just want the hash output.
//!
//! Parameters (matching p3-poseidon2 for Goldilocks):
//!   - Width: 8 state elements
//!   - S-box: x^7 (degree 7, STARK-friendly)
//!   - Full rounds: 8 (4 initial + 4 terminal)
//!   - Partial rounds: 22 (S-box on element 0 only)
//!   - Total: 30 rounds per permutation
//!   - Sponge rate: 4, capacity: 4
//!
//! The round constants are generated from a deterministic seed (splitmix64)
//! so they match between the prover and verifier without shipping a big table.

use p3_goldilocks::Goldilocks;
use p3_field::{PrimeCharacteristicRing, PrimeField64};

/// Poseidon2 parameters for Goldilocks width 8.
pub const WIDTH: usize = 8;
pub const SBOX_DEGREE: u64 = 7;
pub const ROUNDS_F: usize = 8; // 4 initial + 4 terminal
pub const ROUNDS_F_HALF: usize = ROUNDS_F / 2; // 4
pub const ROUNDS_P: usize = 22;
pub const TOTAL_ROUNDS: usize = ROUNDS_F + ROUNDS_P; // 30

/// Internal diagonal matrix for width 8.
/// From p3-goldilocks/src/poseidon2.rs.
pub const MATRIX_DIAG_8: [u64; 8] = [
    0xa98811a1fed4e3a5,
    0x1cc48b54f377e2a0,
    0xe40cd4f6c5609a26,
    0x11de79ebca97a4a3,
    0x9177c73d8b7e929c,
    0x2a6fe8085797e791,
    0x3de6e93329f8d5ad,
    0x3f7af9125da962fe,
];

/// Stored round constants for a Poseidon2 instance.
///
/// Generated deterministically from a seed so both prover and verifier
/// get the same constants without a shared lookup table.
#[derive(Clone, Debug)]
pub struct Poseidon2Constants {
    /// External (full) round constants: ROUNDS_F arrays of WIDTH constants each.
    /// First ROUNDS_F_HALF are initial, last ROUNDS_F_HALF are terminal.
    pub external_rc: Vec<[Goldilocks; WIDTH]>,
    /// Internal (partial) round constants: ROUNDS_P single constants.
    pub internal_rc: Vec<Goldilocks>,
}

/// A simple splitmix64 RNG for deterministic constant generation.
struct SplitMix64(u64);

impl SplitMix64 {
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9e3779b97f4a7c15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
        z ^ (z >> 31)
    }

    fn next_goldilocks(&mut self) -> Goldilocks {
        // Generate a random Goldilocks element by reducing a u64.
        // p3-poseidon2 uses StandardUniform which generates values in [0, p).
        // We mimic this: generate u64, reduce mod p.
        let val = self.next_u64();
        Goldilocks::from_u64(val % Goldilocks::ORDER_U64)
    }
}

impl Poseidon2Constants {
    /// Generate round constants from a deterministic seed.
    /// This MUST match the constants generated by p3-poseidon2's `new_from_rng_128`.
    pub fn from_seed(seed: u64) -> Self {
        let mut rng = SplitMix64(seed);

        // External round constants: ROUNDS_F arrays of WIDTH elements
        let mut external_rc = Vec::with_capacity(ROUNDS_F);
        for _ in 0..ROUNDS_F {
            let mut rc = [Goldilocks::ZERO; WIDTH];
            for j in 0..WIDTH {
                rc[j] = rng.next_goldilocks();
            }
            external_rc.push(rc);
        }

        // Internal round constants: ROUNDS_P single elements
        let mut internal_rc = Vec::with_capacity(ROUNDS_P);
        for _ in 0..ROUNDS_P {
            internal_rc.push(rng.next_goldilocks());
        }

        Self {
            external_rc,
            internal_rc,
        }
    }
}

/// Apply the 4x4 MDS matrix to a 4-element vector.
/// Matrix: [[2,3,1,1],[1,2,3,1],[1,1,2,3],[3,1,1,2]] (circulant).
#[inline]
fn apply_mat4(x: &mut [Goldilocks; 4]) {
    let t01 = x[0] + x[1];
    let t23 = x[2] + x[3];
    let t0123 = t01 + t23;
    let t01123 = t0123 + x[1];
    let t01233 = t0123 + x[3];
    x[3] = t01233 + x[0].double();
    x[1] = t01123 + x[2].double();
    x[0] = t01123 + t01;
    x[2] = t01233 + t23;
}

/// External linear layer for width 8: apply 4x4 MDS to each block, then mix.
/// This matches p3-poseidon2's `mds_light_permutation` for MDSMat4.
fn external_linear_layer(state: &mut [Goldilocks; WIDTH]) {
    // Apply 4x4 MDS to blocks [0..4] and [4..8]
    let mut block0 = [state[0], state[1], state[2], state[3]];
    let mut block1 = [state[4], state[5], state[6], state[7]];
    apply_mat4(&mut block0);
    apply_mat4(&mut block1);

    // Mix: state[i] += sum_of_other_block
    // Actually, the mds_light_permutation formula is:
    // For WIDTH = 2*4: output[i] = 2*M*block[i/4][i%4] + sum(M*block[j])
    // Which simplifies to: output = block_result + sum_of_all_block_results
    // Let me check the exact formula...
    //
    // From p3-poseidon2 external.rs mds_light_permutation:
    // 1. Apply mat4 to each chunk
    // 2. Store sum = sum of all state elements
    // 3. state[i] += sum
    //
    // Wait no, that's not right either. Let me re-read...
    // The code does: sum = chunks[0] + chunks[1] + ... (element-wise for blocks)
    // Then state[i] += sum[i % 4]
    //
    // Actually for WIDTH=8 with 4-element blocks:
    // After apply_mat4 to each block:
    //   For i in 0..4: block_sum[i] = block0[i] + block1[i]
    //   For i in 0..4: state[i] = block0[i] + block_sum[i]
    //   For i in 0..4: state[4+i] = block1[i] + block_sum[i]

    for i in 0..4 {
        let sum = block0[i] + block1[i];
        state[i] = block0[i] + sum;
        state[4 + i] = block1[i] + sum;
    }
}

/// Internal linear layer: matmul_internal with diagonal matrix.
/// Formula: s = sum(state), state[i] = state[i] * diag[i] + s
fn internal_linear_layer(state: &mut [Goldilocks; WIDTH]) {
    let sum: Goldilocks = state.iter().copied().sum();
    for i in 0..WIDTH {
        state[i] = state[i] * Goldilocks::from_u64(MATRIX_DIAG_8[i] % Goldilocks::ORDER_U64) + sum;
    }
}

/// S-box: x^7
#[inline]
fn sbox(x: Goldilocks) -> Goldilocks {
    let x2 = x * x;
    let x3 = x * x2;
    let x4 = x2 * x2;
    x3 * x4
}

/// Full record of all states during a single Poseidon2 permutation.
///
/// states[0] is the input, states[30] is the output. The trace generator
/// uses these to fill 30 constraint rows plus 1 output/gap row.
#[derive(Clone, Debug)]
pub struct Poseidon2Trace {
    /// States: [initial, after_round_0, after_round_1, ..., after_round_29]
    /// Length = TOTAL_ROUNDS + 1 = 31
    pub states: Vec<[Goldilocks; WIDTH]>,
}

/// Run the full Poseidon2 permutation, recording the state after each round.
///
/// This is the workhorse for trace generation: it returns every intermediate
/// state so fill_poseidon2_rows can write them into the trace matrix.
/// For a simple hash (no trace needed), use poseidon2_hash instead.
pub fn poseidon2_permute_traced(
    input: &[Goldilocks; WIDTH],
    constants: &Poseidon2Constants,
) -> Poseidon2Trace {
    let mut states = Vec::with_capacity(TOTAL_ROUNDS + 1);
    let mut state = *input;
    states.push(state);

    // 4 initial full rounds
    for r in 0..ROUNDS_F_HALF {
        // Add round constants
        for i in 0..WIDTH {
            state[i] += constants.external_rc[r][i];
        }
        // S-box all
        for i in 0..WIDTH {
            state[i] = sbox(state[i]);
        }
        // External linear layer
        external_linear_layer(&mut state);
        states.push(state);
    }

    // 22 partial rounds
    for r in 0..ROUNDS_P {
        // Add round constant to element 0 only
        state[0] += constants.internal_rc[r];
        // S-box only element 0
        state[0] = sbox(state[0]);
        // Internal linear layer
        internal_linear_layer(&mut state);
        states.push(state);
    }

    // 4 terminal full rounds
    for r in 0..ROUNDS_F_HALF {
        // Add round constants
        for i in 0..WIDTH {
            state[i] += constants.external_rc[ROUNDS_F_HALF + r][i];
        }
        // S-box all
        for i in 0..WIDTH {
            state[i] = sbox(state[i]);
        }
        // External linear layer
        external_linear_layer(&mut state);
        states.push(state);
    }

    assert_eq!(states.len(), TOTAL_ROUNDS + 1);
    Poseidon2Trace { states }
}

/// Poseidon2 sponge hash (no trace recording, just the result).
///
/// Absorbs `input` in chunks of 4 (the rate), applying a permutation after
/// each chunk. Then squeezes `output_len` elements from the capacity portion.
/// Used when you only need the hash output, not the intermediate states.
pub fn poseidon2_hash(
    input: &[Goldilocks],
    output_len: usize,
    constants: &Poseidon2Constants,
) -> Vec<Goldilocks> {
    let rate = 4;
    let mut state = [Goldilocks::ZERO; WIDTH];

    // Absorb phase
    for chunk in input.chunks(rate) {
        for (i, &val) in chunk.iter().enumerate() {
            state[i] += val;
        }
        let trace = poseidon2_permute_traced(&state, constants);
        state = *trace.states.last().unwrap();
    }

    // Squeeze
    state[..output_len].to_vec()
}

/// Poseidon2 sponge hash that also returns every permutation trace.
///
/// Same logic as poseidon2_hash, but records and returns a Poseidon2Trace
/// for each permutation call. The trace generator (trace.rs) uses these
/// to fill the Poseidon2 section of the STARK execution trace.
pub fn poseidon2_hash_traced(
    input: &[Goldilocks],
    output_len: usize,
    constants: &Poseidon2Constants,
) -> (Vec<Goldilocks>, Vec<Poseidon2Trace>) {
    let rate = 4;
    let mut state = [Goldilocks::ZERO; WIDTH];
    let mut traces = Vec::new();

    // Absorb phase
    for chunk in input.chunks(rate) {
        for (i, &val) in chunk.iter().enumerate() {
            state[i] += val;
        }
        let trace = poseidon2_permute_traced(&state, constants);
        state = *trace.states.last().unwrap();
        traces.push(trace);
    }

    // Squeeze
    let output = state[..output_len].to_vec();
    (output, traces)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_poseidon2_permute_deterministic() {
        let constants = Poseidon2Constants::from_seed(42);
        let input = [Goldilocks::ZERO; WIDTH];
        let trace = poseidon2_permute_traced(&input, &constants);
        let output = trace.states.last().unwrap();

        // Should be deterministic
        let trace2 = poseidon2_permute_traced(&input, &constants);
        let output2 = trace2.states.last().unwrap();
        assert_eq!(output, output2);

        // Output should differ from input
        assert_ne!(&input, output);
    }

    #[test]
    fn test_poseidon2_hash_simple() {
        let constants = Poseidon2Constants::from_seed(42);
        let input = [Goldilocks::from_u64(1), Goldilocks::from_u64(2)];
        let output = poseidon2_hash(&input, 4, &constants);
        assert_eq!(output.len(), 4);

        // Different input should give different output
        let input2 = [Goldilocks::from_u64(3), Goldilocks::from_u64(4)];
        let output2 = poseidon2_hash(&input2, 4, &constants);
        assert_ne!(output, output2);
    }

    #[test]
    fn test_poseidon2_trace_consistency() {
        let constants = Poseidon2Constants::from_seed(42);
        let input = [
            Goldilocks::from_u64(1),
            Goldilocks::from_u64(2),
            Goldilocks::from_u64(3),
        ];
        let (output, traces) = poseidon2_hash_traced(&input, 4, &constants);
        let output_simple = poseidon2_hash(&input, 4, &constants);
        assert_eq!(output, output_simple);
        assert_eq!(traces.len(), 1); // 3 elements < rate=4, so 1 permutation
    }
}
